# Generated by Django 2.1.5 on 2019-01-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_rti_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
